<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container39JqJyJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container39JqJyJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container39JqJyJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container39JqJyJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container39JqJyJ\App_KernelDevDebugContainer([
    'container.build_hash' => '39JqJyJ',
    'container.build_id' => 'a0fc626b',
    'container.build_time' => 1600331386,
], __DIR__.\DIRECTORY_SEPARATOR.'Container39JqJyJ');
