<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPJNoQRt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPJNoQRt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPJNoQRt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPJNoQRt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPJNoQRt\App_KernelDevDebugContainer([
    'container.build_hash' => 'PJNoQRt',
    'container.build_id' => '64d7f1bc',
    'container.build_time' => 1599817743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPJNoQRt');
