<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVWqqfNG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVWqqfNG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVWqqfNG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVWqqfNG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVWqqfNG\App_KernelDevDebugContainer([
    'container.build_hash' => 'VWqqfNG',
    'container.build_id' => 'c957b232',
    'container.build_time' => 1600330156,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVWqqfNG');
